title: "Cristhian"
email: your.email@example.com   # optional
description: "Curriculum and projects"
url: "https://crackbandicoot-dot.github.io"
baseurl: ""
repository: crackbandicoot-dot/crackbandicoot-dot.github.io

# Theme
remote_theme: daattali/beautiful-jekyll

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: page
